@extends('layout.base')

@section('content')
<div class="container">
    <div class="row py-5">
        <h4 class="mb-4">Politicas de envio</h4>
        <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ac ligula nec nisi mollis pretium sed non augue. Etiam nunc justo, sagittis vel sapien vel, pellentesque accumsan turpis. Nam quis urna id est placerat ultrices. Duis neque urna, sollicitudin ac nulla a, aliquam accumsan nibh. Aliquam pellentesque orci quis nunc viverra faucibus. Pellentesque facilisis ligula vitae interdum venenatis. Aenean id rutrum eros, a faucibus libero. Vivamus odio est, faucibus sed vestibulum non, suscipit sit amet mauris. Curabitur dignissim, erat laoreet molestie consectetur, risus dui semper nisl, eget aliquet augue nunc sed urna. Proin volutpat leo risus, ac faucibus purus porttitor non. Phasellus vitae pharetra risus. Phasellus laoreet pellentesque pretium.</p>
        <p class="text-justify">Duis iaculis sagittis condimentum. Maecenas vel rutrum quam, sollicitudin fringilla nisl. In hac habitasse platea dictumst. Cras ac condimentum nisl. Proin urna libero, scelerisque sit amet diam nec, commodo semper dui. Aliquam et neque vel nisi dapibus scelerisque. Suspendisse potenti. Etiam sed diam faucibus nulla blandit tempus et vel tellus. Donec nunc arcu, sagittis sit amet mauris vel, faucibus sodales ipsum. In hac habitasse platea dictumst. Aliquam erat volutpat. Duis sapien sapien, elementum ut eleifend eu, luctus venenatis ante.</p>
        <p class="text-justify">Mauris orci quam, eleifend eget eros ac, malesuada cursus quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus sed suscipit tellus. In velit nunc, auctor ac mollis id, cursus quis nulla. Etiam accumsan posuere orci, quis dictum mi egestas eget. Phasellus pellentesque quis sapien a efficitur. Sed non porttitor orci.</p>
        <p class="text-justify">Pellentesque porta magna gravida velit laoreet, sed tincidunt ante faucibus. Suspendisse ornare diam quis sem dictum consequat. Aenean orci justo, aliquet eu lorem sed, finibus volutpat erat. Nulla hendrerit magna id maximus mollis. Pellentesque sit amet massa vitae purus tincidunt egestas quis eget mauris. Proin elementum sapien quis malesuada blandit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur sed dui iaculis, aliquam ex in, pretium lorem. Cras nec volutpat quam. Morbi pulvinar congue metus in imperdiet. Quisque in diam id lorem sollicitudin placerat.</p>
        <p class="text-justify">Praesent porta, massa et blandit lobortis, urna purus aliquam libero, in lobortis ligula orci sit amet erat. Phasellus a lectus ultricies, posuere augue non, molestie orci. Phasellus eget elit vitae lectus hendrerit scelerisque. Nullam ullamcorper sodales turpis, ac molestie quam pharetra a. Sed iaculis posuere felis eget tincidunt. Pellentesque commodo, ligula eget lobortis vestibulum, erat velit eleifend ipsum, ac tincidunt augue nulla sed nibh. Morbi sed purus mi. Fusce id sapien vitae orci tempus pellentesque vitae nec odio. Sed imperdiet feugiat erat sed sollicitudin. Nulla ornare tortor ut lacus accumsan tempor. Quisque sapien ligula, aliquam eu tellus ut, bibendum ornare lorem. Integer lobortis nisi in arcu blandit mattis. Nulla feugiat, tortor vitae mattis maximus, nunc mauris sagittis massa, quis lacinia nulla risus id tortor.</p>
    </div>
</div>
@endsection